repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      types: [python]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      types: [python]