matrix:
  include:
    - language: python
      python: 3.6
      addons:
          apt:
            update: true
            packages:
              - python3-pip
      before_script:
      - pip3 install flask
      - pip3 install flask_restful
      - pip3 install flask_socketio
      - pip3 install lizard
      - lizard web
      - cd web/test
      script:
      - PYTHON_UNIT_TEST=true python unit-test.py
      - PYTHON_UNIT_TEST=true python backend-module-test.py

    - language: c
      compiler: clang
      addons:
          apt:
            update: true
            packages:
              - python3
              - python3-pip
              - cppcheck
              - libaio-dev
              - libjson-c-dev
              - libjemalloc-dev
              - llvm-6.0
              - clang-6.0
              - libclang-6.0-dev
      before_script:
      - sudo ln -s /usr/bin/clang-6.0 /usr/bin/clang
      - pip3 install scons-compiledb
      - pip3 install scons
      - pip3 install clang-format 
      - pip3 install lizard
      - lizard runner && lizard include
      script:
      - scons

notifications:
  email:
  - ss5kijun@gmail.com
