matrix:
  include:
    - language: python
      python: 3.6
      addons:
          apt:
            update: true
            packages:
              - python3-pip
      before_script:
      - pip3 install flask
      - pip3 install flask_restful
      - pip3 install flask_socketio
      - cd web/test
      script:
      - python unit-test.py
      - python backend-module-test.py

    - language: c
      compiler: gcc
      addons:
          apt:
            update: true
            packages:
              - python3
              - python3-pip
              - cppcheck
              - libaio-dev
              - libjson-c-dev
              - libjemalloc-dev
      before_script:
      - pip3 install scons-compiledb
      - pip3 install scons
      - pip3 install clang-format 
      script:
      - scons

notifications:
  email:
  - ss5kijun@gmail.com
